baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Tinlake'

[params.identity]
  logo = 'tinlake_logo.svg'

[menus]
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 1
  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 2
  [[menus.main]]
    name = 'Contacts'
    pageRef = '/contacts'
    weight = 3
  [[menus.main]]
    name = 'Research'
    pageRef = '/research'
    weight = 4
  [[menus.main]]
    name = 'Get a quote'
    pageRef = '/get-a-quote'
    weight = 5